apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  name: mys3bucket
  namespace: openshift-adp
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: mys3bucket-mydemo-10000000
  generateBucketName: mys3bucket
  objectBucketName: obc-openshift-adp-mys3bucket
  storageClassName: openshift-storage.noobaa.io

