apiVersion: olm.operatorframework.io/v1
kind: ClusterCatalog
metadata:
  annotations:
    createdAt: Thursday, 29-May-25 22:08:12 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: v0.2.0-alpha.1-398-gc2b5dab
  name: cc-redhat-operator-index-v4-18
spec:
  priority: 0
  source:
    image:
      ref: quay.local.momolab.io:443/mirror/redhat/redhat-operator-index:v4.18
    type: Image
status: {}
