---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  annotations:
    createdAt: Tuesday, 24-Jun-25 11:25:01 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: v0.2.0-alpha.1-398-gc2b5dab
  name: idms-release-0
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
status: {}
---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  annotations:
    createdAt: Tuesday, 24-Jun-25 11:25:01 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: v0.2.0-alpha.1-398-gc2b5dab
  name: idms-operator-0
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.local.momolab.io:443/mirror/gitlab-org/gl-openshift/gitlab-runner-operator
    source: registry.gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator
  - mirrors:
    - quay.local.momolab.io:443/mirror/konveyor
    source: quay.io/konveyor
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - quay.local.momolab.io:443/mirror/datagrid
    source: registry.redhat.io/datagrid
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift
    source: quay.io/openshift
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhceph
    source: registry.redhat.io/rhceph
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-service-mesh
    source: registry.redhat.io/openshift-service-mesh
  - mirrors:
    - quay.local.momolab.io:443/mirror/gitlab-org/ci-cd/gitlab-runner-ubi-images
    source: registry.gitlab.com/gitlab-org/ci-cd/gitlab-runner-ubi-images
  - mirrors:
    - quay.local.momolab.io:443/mirror/lvms4
    source: registry.redhat.io/lvms4
  - mirrors:
    - quay.local.momolab.io:443/mirror/ansible-automation-platform
    source: registry.redhat.io/ansible-automation-platform
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhel8
    source: registry.redhat.io/rhel8
  - mirrors:
    - quay.local.momolab.io:443/mirror/ansible-automation-platform-24
    source: registry.redhat.io/ansible-automation-platform-24
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-service-mesh-tech-preview
    source: registry.redhat.io/openshift-service-mesh-tech-preview
  - mirrors:
    - quay.local.momolab.io:443/mirror/prometheus
    source: quay.io/prometheus
  - mirrors:
    - quay.local.momolab.io:443/mirror/quay
    source: registry.redhat.io/quay
  - mirrors:
    - quay.local.momolab.io:443/mirror/skupper
    source: quay.io/skupper
  - mirrors:
    - quay.local.momolab.io:443/mirror/gitlab-org/cloud-native
    source: registry.gitlab.com/gitlab-org/cloud-native
  - mirrors:
    - quay.local.momolab.io:443/mirror/odf4
    source: registry.redhat.io/odf4
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhbk
    source: registry.redhat.io/rhbk
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhel9
    source: registry.redhat.io/rhel9
  - mirrors:
    - quay.local.momolab.io:443/mirror/argoprojlabs
    source: quay.io/argoprojlabs
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-service-mesh-dev-preview-beta
    source: registry.redhat.io/openshift-service-mesh-dev-preview-beta
  - mirrors:
    - quay.local.momolab.io:443/mirror/ubi8
    source: registry.redhat.io/ubi8
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-gitops-1
    source: registry.redhat.io/openshift-gitops-1
  - mirrors:
    - quay.local.momolab.io:443/mirror/ansible-automation-platform-25
    source: registry.redhat.io/ansible-automation-platform-25
  - mirrors:
    - quay.local.momolab.io:443/mirror/service-interconnect
    source: registry.redhat.io/service-interconnect
  - mirrors:
    - quay.local.momolab.io:443/mirror/gitlab-org/gl-openshift/gitlab-runner-operator/openshift4
    source: registry.gitlab.com/gitlab-org/gl-openshift/gitlab-runner-operator/openshift4
  - mirrors:
    - quay.local.momolab.io:443/mirror/community-operator-pipeline-prod
    source: quay.io/community-operator-pipeline-prod
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-community-operators
    source: quay.io/openshift-community-operators
  - mirrors:
    - quay.local.momolab.io:443/mirror/rh-sso-7
    source: registry.redhat.io/rh-sso-7
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhacm2
    source: registry.redhat.io/rhacm2
status: {}
