---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  annotations:
    createdAt: Thursday, 29-May-25 22:08:12 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: v0.2.0-alpha.1-398-gc2b5dab
  name: idms-release-0
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
status: {}
---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  annotations:
    createdAt: Thursday, 29-May-25 22:08:12 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: v0.2.0-alpha.1-398-gc2b5dab
  name: idms-operator-0
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.local.momolab.io:443/mirror/quay
    source: registry.redhat.io/quay
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhel9
    source: registry.redhat.io/rhel9
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhel8
    source: registry.redhat.io/rhel8
  - mirrors:
    - quay.local.momolab.io:443/mirror/lvms4
    source: registry.redhat.io/lvms4
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-gitops-1
    source: registry.redhat.io/openshift-gitops-1
  - mirrors:
    - quay.local.momolab.io:443/mirror/rh-sso-7
    source: registry.redhat.io/rh-sso-7
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhbk
    source: registry.redhat.io/rhbk
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhacm2
    source: registry.redhat.io/rhacm2
status: {}
