---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  annotations:
    createdAt: Tuesday, 24-Jun-25 11:25:01 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: v0.2.0-alpha.1-398-gc2b5dab
  name: itms-release-0
spec:
  imageTagMirrors:
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
status: {}
---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  annotations:
    createdAt: Tuesday, 24-Jun-25 11:25:01 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: v0.2.0-alpha.1-398-gc2b5dab
  name: itms-operator-0
spec:
  imageTagMirrors:
  - mirrors:
    - quay.local.momolab.io:443/mirror/infinispan
    source: quay.io/infinispan
  - mirrors:
    - quay.local.momolab.io:443/mirror/opstree
    source: quay.io/opstree
  - mirrors:
    - quay.local.momolab.io:443/mirror/percona
    source: docker.io/percona
  - mirrors:
    - quay.local.momolab.io:443/mirror/keycloak
    source: quay.io/keycloak
  - mirrors:
    - quay.local.momolab.io:443/mirror/epamedp
    source: docker.io/epamedp
status: {}
---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  annotations:
    createdAt: Tuesday, 24-Jun-25 11:25:01 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: v0.2.0-alpha.1-398-gc2b5dab
  name: itms-generic-0
spec:
  imageTagMirrors:
  - mirrors:
    - quay.local.momolab.io:443/mirror/ubi9
    source: registry.redhat.io/ubi9
  - mirrors:
    - quay.local.momolab.io:443/mirror/ubi8
    source: registry.redhat.io/ubi8
status: {}
