apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    createdAt: Friday, 31-Jul-26 07:00:03 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: 4.22.0-202606091155.p2.g41d68b1.assembly.stream.el9-41d68b1
  name: cs-community-operator-index-v4-21
  namespace: openshift-marketplace
spec:
  image: quay.local.momolab.io:443/mirror/redhat/community-operator-index:v4.21
  sourceType: grpc
