---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  annotations:
    createdAt: Thursday, 06-Aug-26 08:34:14 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: 4.22.0-202606091155.p2.g41d68b1.assembly.stream.el9-41d68b1
  name: idms-operator-redhat
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-pipelines
    source: registry.redhat.io/openshift-pipelines
  - mirrors:
    - quay.local.momolab.io:443/mirror/odf4
    source: registry.redhat.io/odf4
  - mirrors:
    - quay.local.momolab.io:443/mirror/kmm
    source: registry.redhat.io/kmm
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-logging
    source: registry.redhat.io/openshift-logging
  - mirrors:
    - quay.local.momolab.io:443/mirror/external-secrets-operator
    source: registry.redhat.io/external-secrets-operator
  - mirrors:
    - quay.local.momolab.io:443/mirror/multicluster-engine
    source: registry.redhat.io/multicluster-engine
  - mirrors:
    - quay.local.momolab.io:443/mirror/ubi9
    source: registry.redhat.io/ubi9
  - mirrors:
    - quay.local.momolab.io:443/mirror/web-terminal
    source: registry.redhat.io/web-terminal
  - mirrors:
    - quay.local.momolab.io:443/mirror/quay
    source: registry.redhat.io/quay
  - mirrors:
    - quay.local.momolab.io:443/mirror/oadp
    source: registry.redhat.io/oadp
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhel8
    source: registry.redhat.io/rhel8
  - mirrors:
    - quay.local.momolab.io:443/mirror/source-to-image
    source: registry.redhat.io/source-to-image
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhacm2
    source: registry.redhat.io/rhacm2
  - mirrors:
    - quay.local.momolab.io:443/mirror/ansible-automation-platform-tech-preview
    source: registry.redhat.io/ansible-automation-platform-tech-preview
  - mirrors:
    - quay.local.momolab.io:443/mirror/migration-toolkit-virtualization
    source: registry.redhat.io/migration-toolkit-virtualization
  - mirrors:
    - quay.local.momolab.io:443/mirror/ubi9
    source: registry.access.redhat.com/ubi9
  - mirrors:
    - quay.local.momolab.io:443/mirror/devspaces
    source: registry.redhat.io/devspaces
  - mirrors:
    - quay.local.momolab.io:443/mirror/network-observability
    source: registry.redhat.io/network-observability
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-service-mesh
    source: registry.redhat.io/openshift-service-mesh
  - mirrors:
    - quay.local.momolab.io:443/mirror/ansible-automation-platform-26
    source: registry.redhat.io/ansible-automation-platform-26
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-update-service
    source: registry.redhat.io/openshift-update-service
  - mirrors:
    - quay.local.momolab.io:443/mirror/devworkspace
    source: registry.redhat.io/devworkspace
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhceph
    source: registry.redhat.io/rhceph
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhel9
    source: registry.redhat.io/rhel9
  - mirrors:
    - quay.local.momolab.io:443/mirror/lvms4
    source: registry.redhat.io/lvms4
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-serverless-1
    source: registry.redhat.io/openshift-serverless-1
  - mirrors:
    - quay.local.momolab.io:443/mirror/advanced-cluster-security
    source: registry.redhat.io/advanced-cluster-security
  - mirrors:
    - quay.local.momolab.io:443/mirror/rhbk
    source: registry.redhat.io/rhbk
  - mirrors:
    - quay.local.momolab.io:443/mirror/container-native-virtualization
    source: registry.redhat.io/container-native-virtualization
  - mirrors:
    - quay.local.momolab.io:443/mirror/compliance
    source: registry.redhat.io/compliance
  - mirrors:
    - quay.local.momolab.io:443/mirror/cluster-observability-operator
    source: registry.redhat.io/cluster-observability-operator
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift-gitops-1
    source: registry.redhat.io/openshift-gitops-1
  - mirrors:
    - quay.local.momolab.io:443/mirror/cert-manager
    source: registry.redhat.io/cert-manager
  - mirrors:
    - quay.local.momolab.io:443/mirror/ansible-automation-platform
    source: registry.redhat.io/ansible-automation-platform
  - mirrors:
    - quay.local.momolab.io:443/mirror/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - quay.local.momolab.io:443/mirror/ansible-automation-platform-27
    source: registry.redhat.io/ansible-automation-platform-27
