---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  annotations:
    createdAt: Thursday, 06-Aug-26 08:43:09 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: 4.22.0-202606091155.p2.g41d68b1.assembly.stream.el9-41d68b1
  name: itms-operator-certified
spec:
  imageTagMirrors:
  - mirrors:
    - quay.local.momolab.io:443/mirror/mariadb-operator
    source: ghcr.io/mariadb-operator
