# oc create secret generic htpass-secret --from-file=htpasswd=./htpasswd-all -n openshift-config
# Note, htpasswd-all has admin:password and developer:password
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: my_htpasswd_provider 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret 


