apiVersion: v1
kind: Pod
metadata:
  name: test-verification
spec:
  containers:
    - name: test
      image: quay.local.momolab.io:443/mirror/ubi9/ubi:latest
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Never

