apiVersion: v1
kind: Pod
metadata:
  name: test-verification-no-sig
spec:
  containers:
    - name: test-no-sig
      #image: quay.local.momolab.io:443/mirror/ubi9/ubi:latest
      image: quay.local.momolab.io:443/mirror/ubi9/ubi:no-sig
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Never

