kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
archiveSize: 16
mirror:
  platform:
    channels:
    - name: stable-4.18
      minVersion: 4.18.13
      maxVersion: 4.18.13
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
    full: false
    packages:
      - name: advanced-cluster-management
#      - name: ansible-automation-platform-operator
#      - name: datagrid
      - name: lvms-operator
#      - name: mcg-operator
#      - name: odf-operator
#      - name: ocs-client-operator
#      - name: ocs-operator
#      - name: odf-csi-addons-operator
#      - name: odf-multicluster-orchestrator
#      - name: odr-cluster-operator
      - name: openshift-gitops-operator
      - name: quay-operator
      - name: rhbk-operator
      - name: rhsso-operator
#      - name: servicemeshoperator
#      - name: servicemeshoperator3
#      - name: skupper-operator
#      - name: submariner
#  - catalog: registry.redhat.io/redhat/certified-operator-index:v4.18
#    full: false
#    packages:
#      - name: crunchy-postgres-operator
#      - name: cockroachdb-certified
#      - name: gitlab-operator-kubernetes
#      - name: gitlab-runner-operator
#  - catalog: registry.redhat.io/redhat/community-operator-index:v4.18
#    full: false
#    packages:
#      - name: argocd-operator
#      - name: infinispan
#      - name: keycloak-operator
#      - name: mongodb-operator
#      - name: oadp-operator
#      - name: skupper-operator
  additionalImages:
   - name: registry.redhat.io/ubi8/ubi:latest
   - name: registry.redhat.io/ubi9/ubi:latest

