apiVersion: velero.io/v1
kind: Backup
metadata:
  name: odaptestbackup
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  hooks: {}
  includedNamespaces:
  - odaptest
  includedResources: [] 
  excludedResources: [] 
  storageLocation: default
  ttl: 720h0m0s
  labelSelector: 
    matchLabels:
      app: backend
  orLabelSelectors: 
  - matchLabels:
      app: backend  

