apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-gitops-operator-mgo
  namespace: openshift-gitops-operator
spec:
  upgradeStrategy: Default
status:
  namespaces:
  - ""
