apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    createdAt: Sunday, 28-Sep-25 12:23:18 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: 4.19.0-202508130123.p2.ge91ec32.assembly.stream.el9-e91ec32
  name: redhat-operators
  namespace: openshift-marketplace
spec:
  image: quay.local.momolab.io:443/mirror/redhat/redhat-operator-index:v4.19
  sourceType: grpc
status: {}
