apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators
  namespace: openshift-marketplace
spec:
  image: registry.local.momolab.io:8443/mirror/redhat/redhat-operator-index:v4.14
  sourceType: grpc
status: {}
