---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: itms-generic-0
spec:
  imageTagMirrors:
  - mirrors:
    - registry.local.momolab.io:8443/mirror/ubi8
    source: registry.redhat.io/ubi8
    mirrorSourcePolicy: NeverContactSource
status: {}
---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: itms-release-0
spec:
  imageTagMirrors:
  - mirrors:
    - registry.local.momolab.io:8443/mirror/openshift-release-dev
    source: quay.io/openshift-release-dev
    mirrorSourcePolicy: NeverContactSource
status: {}
---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: itms-operator-0
spec:
  imageTagMirrors:
  - mirrors:
    - registry.local.momolab.io:8443/mirror/keycloak
    source: quay.io/keycloak
    mirrorSourcePolicy: NeverContactSource
  - mirrors:
    - registry.local.momolab.io:8443/mirror/opstree
    source: quay.io/opstree
    mirrorSourcePolicy: NeverContactSource
  - mirrors:
    - registry.local.momolab.io:8443/mirror/infinispan
    source: quay.io/infinispan
    mirrorSourcePolicy: NeverContactSource
status: {}
