# This playbook creates the agent ISO for each SNO cluster
---
- name: Prepare agent ISO for each SNO
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../myvars/external_vars.yaml
  tasks:

    - name: Restore install-config.yaml and agent-config.yaml from backup
      ansible.builtin.copy:
        src: "{{ myworkdir }}/{{ item[0] }}/{{ item[1] }}.bak"
        dest: "{{ myworkdir }}/{{ item[0] }}/ocp/{{ item[1] }}"
        remote_src: true
      loop: "{{ snos | product(['install-config.yaml', 'agent-config.yaml']) | list }}"

    - name: Enable IPSec by copying cluster-network-03-config.yml
      ansible.builtin.template:
        src: ../templates/cluster-network-03-config.yml.j2
        dest: "{{ myworkdir }}/{{ item }}/ocp/openshift/cluster-network-03-config.yml"
        mode: "0644"
      loop: "{{ snos }}"
      when: ipsec_enabled

    - name: Template machineconfig for kernel args
      ansible.builtin.template:
        src: ../templates/machineconfig-kargs.yaml.j2
        dest: "{{ myworkdir }}/{{ item }}/ocp/openshift/99-openshift-machineconfig-kargs.yaml"
        mode: "0644"
      loop: "{{ snos }}"

    - name: Generate agent ISO
      ansible.builtin.shell: |
        {{ myworkdir }}/openshift-install --dir={{ myworkdir }}/{{ item }}/ocp agent create image
      loop: "{{ snos }}"
      loop_control:
        label: "{{ item }}"

    - name: Assert agent ISO exists
      ansible.builtin.stat:
        path: "{{ myworkdir }}/{{ item }}/ocp/agent.{{ OCP_ARCH }}.iso"
      register: iso_stat
      failed_when: not iso_stat.stat.exists
      loop: "{{ snos }}"
