# This playbook builds the VMs for each SNO cluster
---
  - name: Build VMs for each SNO cluster
    hosts: localhost
    connection: local
    gather_facts: no
    vars_files:
      - ../myvars/external_vars.yaml

    tasks:
 
      - name: Create SNO VMs
        ansible.builtin.command: >-
          virt-install
          --name {{ item }}
          --hvm
          --virt-type kvm
          --disk path={{ myworkdir }}/{{ item }}/ocp/agent.{{ OCP_ARCH }}.iso,device=cdrom
          --arch {{ OCP_ARCH }}
          --os-variant rhel8.0
          --network network="{{ bridged_network_name }}",mac="{{ mac_prefix }}:{{ snoclusters[item].mac_nr }}",model=virtio
          --vcpus {{ snoclusters[item].vcpus }}
          --ram {{ snoclusters[item].ram }}
          --disk path={{ libvirtpooldir }}{{ item }}-root.qcow2,size={{ snoclusters[item].disk }},format=qcow2,bus=virtio,cache={{ snoclusters[item].cache }}
          --disk path={{ libvirtpooldir }}{{ item }}-data.qcow2,size={{ snoclusters[item].disk2 }},format=qcow2,bus=virtio,cache={{ snoclusters[item].cache2 }}
          --check disk_size=off
          --graphics spice,listen=127.0.0.1
          --noautoconsole
          --import
          --boot uefi,menu=on,useserial=on,hd,cdrom
        with_items: "{{ snos }}"
        retries: 10
        delay: 10
        register: vm_creation
        until: vm_creation is not failed
        become: true

      - name: Wait for bootstrap-complete on {{ item }}
        ansible.builtin.shell: |
          {{ myworkdir }}/openshift-install --dir={{ myworkdir }}/{{ item }}/ocp \
            agent wait-for bootstrap-complete --log-level=info
        loop: "{{ snos }}"
        loop_control:
          label: "{{ item }}"
        register: bootstrap_complete
        until: bootstrap_complete is not failed
        retries: 2
        delay: 30

      - name: Wait for install-complete on {{ item }}
        ansible.builtin.shell: |
          {{ myworkdir }}/openshift-install --dir={{ myworkdir }}/{{ item }}/ocp \
            agent wait-for install-complete --log-level=info
        loop: "{{ snos }}"
        loop_control:
          label: "{{ item }}"
        register: install_complete
        until: install_complete is not failed
        retries: 3
        delay: 30

      - name: Fetch kubeconfig file
        ansible.posix.synchronize:
          mode: pull
          src: "{{ myworkdir }}/{{ item }}/ocp/auth/kubeconfig"
          dest: "~/{{ item }}-kubeconfig"
        with_items: "{{ snos }}"
 
      - name: Fix permissions
        ansible.builtin.shell: |
          chmod 0600 "/home/momo/{{ item }}-kubeconfig"
        with_items: "{{ snos }}"

